spring:
    datasource:
        url: jdbc:mysql://localhost:3306/toDoApp
        username: root
        password: rootPass
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: create  # crea/actualiza tablas seg√∫n tus entidades
        show-sql: true       # muestra SQL en consola
        properties:
            hibernate:
                format_sql: true